// flow-typed signature: 2d5a362873d9573161edc6d54c0b0190
// flow-typed version: <<STUB>>/rehype-parse_v4.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rehype-parse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rehype-parse" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "rehype-parse/index" {
  declare module.exports: $Exports<"rehype-parse">;
}
declare module "rehype-parse/index.js" {
  declare module.exports: $Exports<"rehype-parse">;
}
