// flow-typed signature: 89f8074b9679446826e4641701539150
// flow-typed version: <<STUB>>/aphrodite_v1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aphrodite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "aphrodite" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "aphrodite/coverage/prettify" {
  declare module.exports: any;
}

declare module "aphrodite/coverage/sorter" {
  declare module.exports: any;
}

declare module "aphrodite/dist/aphrodite" {
  declare module.exports: any;
}

declare module "aphrodite/dist/aphrodite.umd" {
  declare module.exports: any;
}

declare module "aphrodite/dist/aphrodite.umd.min" {
  declare module.exports: any;
}

declare module "aphrodite/examples/runkit" {
  declare module.exports: any;
}

declare module "aphrodite/examples/server" {
  declare module.exports: any;
}

declare module "aphrodite/examples/src/examples-ssr" {
  declare module.exports: any;
}

declare module "aphrodite/examples/src/examples" {
  declare module.exports: any;
}

declare module "aphrodite/examples/src/StyleTester" {
  declare module.exports: any;
}

declare module "aphrodite/examples/webpack.config" {
  declare module.exports: any;
}

declare module "aphrodite/lib/exports" {
  declare module.exports: any;
}

declare module "aphrodite/lib/generate" {
  declare module.exports: any;
}

declare module "aphrodite/lib/index" {
  declare module.exports: any;
}

declare module "aphrodite/lib/inject" {
  declare module.exports: any;
}

declare module "aphrodite/lib/no-important" {
  declare module.exports: any;
}

declare module "aphrodite/lib/ordered-elements" {
  declare module.exports: any;
}

declare module "aphrodite/lib/staticPrefixData" {
  declare module.exports: any;
}

declare module "aphrodite/lib/util" {
  declare module.exports: any;
}

declare module "aphrodite/no-important" {
  declare module.exports: any;
}

declare module "aphrodite/src/exports" {
  declare module.exports: any;
}

declare module "aphrodite/src/generate" {
  declare module.exports: any;
}

declare module "aphrodite/src/index" {
  declare module.exports: any;
}

declare module "aphrodite/src/inject" {
  declare module.exports: any;
}

declare module "aphrodite/src/no-important" {
  declare module.exports: any;
}

declare module "aphrodite/src/ordered-elements" {
  declare module.exports: any;
}

declare module "aphrodite/src/util" {
  declare module.exports: any;
}

declare module "aphrodite/tests/generate_test" {
  declare module.exports: any;
}

declare module "aphrodite/tests/index_test" {
  declare module.exports: any;
}

declare module "aphrodite/tests/inject_test" {
  declare module.exports: any;
}

declare module "aphrodite/tests/no-important_test" {
  declare module.exports: any;
}

declare module "aphrodite/tests/ordered-elements_test" {
  declare module.exports: any;
}

declare module "aphrodite/tests/util_test" {
  declare module.exports: any;
}

declare module "aphrodite/tools/generate_prefixer_data" {
  declare module.exports: any;
}

declare module "aphrodite/webpack.config" {
  declare module.exports: any;
}

// Filename aliases
declare module "aphrodite/coverage/prettify.js" {
  declare module.exports: $Exports<"aphrodite/coverage/prettify">;
}
declare module "aphrodite/coverage/sorter.js" {
  declare module.exports: $Exports<"aphrodite/coverage/sorter">;
}
declare module "aphrodite/dist/aphrodite.js" {
  declare module.exports: $Exports<"aphrodite/dist/aphrodite">;
}
declare module "aphrodite/dist/aphrodite.umd.js" {
  declare module.exports: $Exports<"aphrodite/dist/aphrodite.umd">;
}
declare module "aphrodite/dist/aphrodite.umd.min.js" {
  declare module.exports: $Exports<"aphrodite/dist/aphrodite.umd.min">;
}
declare module "aphrodite/examples/runkit.js" {
  declare module.exports: $Exports<"aphrodite/examples/runkit">;
}
declare module "aphrodite/examples/server.js" {
  declare module.exports: $Exports<"aphrodite/examples/server">;
}
declare module "aphrodite/examples/src/examples-ssr.js" {
  declare module.exports: $Exports<"aphrodite/examples/src/examples-ssr">;
}
declare module "aphrodite/examples/src/examples.js" {
  declare module.exports: $Exports<"aphrodite/examples/src/examples">;
}
declare module "aphrodite/examples/src/StyleTester.js" {
  declare module.exports: $Exports<"aphrodite/examples/src/StyleTester">;
}
declare module "aphrodite/examples/webpack.config.js" {
  declare module.exports: $Exports<"aphrodite/examples/webpack.config">;
}
declare module "aphrodite/lib/exports.js" {
  declare module.exports: $Exports<"aphrodite/lib/exports">;
}
declare module "aphrodite/lib/generate.js" {
  declare module.exports: $Exports<"aphrodite/lib/generate">;
}
declare module "aphrodite/lib/index.js" {
  declare module.exports: $Exports<"aphrodite/lib/index">;
}
declare module "aphrodite/lib/inject.js" {
  declare module.exports: $Exports<"aphrodite/lib/inject">;
}
declare module "aphrodite/lib/no-important.js" {
  declare module.exports: $Exports<"aphrodite/lib/no-important">;
}
declare module "aphrodite/lib/ordered-elements.js" {
  declare module.exports: $Exports<"aphrodite/lib/ordered-elements">;
}
declare module "aphrodite/lib/staticPrefixData.js" {
  declare module.exports: $Exports<"aphrodite/lib/staticPrefixData">;
}
declare module "aphrodite/lib/util.js" {
  declare module.exports: $Exports<"aphrodite/lib/util">;
}
declare module "aphrodite/no-important.js" {
  declare module.exports: $Exports<"aphrodite/no-important">;
}
declare module "aphrodite/src/exports.js" {
  declare module.exports: $Exports<"aphrodite/src/exports">;
}
declare module "aphrodite/src/generate.js" {
  declare module.exports: $Exports<"aphrodite/src/generate">;
}
declare module "aphrodite/src/index.js" {
  declare module.exports: $Exports<"aphrodite/src/index">;
}
declare module "aphrodite/src/inject.js" {
  declare module.exports: $Exports<"aphrodite/src/inject">;
}
declare module "aphrodite/src/no-important.js" {
  declare module.exports: $Exports<"aphrodite/src/no-important">;
}
declare module "aphrodite/src/ordered-elements.js" {
  declare module.exports: $Exports<"aphrodite/src/ordered-elements">;
}
declare module "aphrodite/src/util.js" {
  declare module.exports: $Exports<"aphrodite/src/util">;
}
declare module "aphrodite/tests/generate_test.js" {
  declare module.exports: $Exports<"aphrodite/tests/generate_test">;
}
declare module "aphrodite/tests/index_test.js" {
  declare module.exports: $Exports<"aphrodite/tests/index_test">;
}
declare module "aphrodite/tests/inject_test.js" {
  declare module.exports: $Exports<"aphrodite/tests/inject_test">;
}
declare module "aphrodite/tests/no-important_test.js" {
  declare module.exports: $Exports<"aphrodite/tests/no-important_test">;
}
declare module "aphrodite/tests/ordered-elements_test.js" {
  declare module.exports: $Exports<"aphrodite/tests/ordered-elements_test">;
}
declare module "aphrodite/tests/util_test.js" {
  declare module.exports: $Exports<"aphrodite/tests/util_test">;
}
declare module "aphrodite/tools/generate_prefixer_data.js" {
  declare module.exports: $Exports<"aphrodite/tools/generate_prefixer_data">;
}
declare module "aphrodite/webpack.config.js" {
  declare module.exports: $Exports<"aphrodite/webpack.config">;
}
