// flow-typed signature: 2c8f0b37c34ec9310b26eae1f00ab18c
// flow-typed version: <<STUB>>/asciidoctor.js_v1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'asciidoctor.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "asciidoctor.js" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "asciidoctor.js/dist/asciidoctor" {
  declare module.exports: any;
}

// Filename aliases
declare module "asciidoctor.js/dist/asciidoctor.js" {
  declare module.exports: $Exports<"asciidoctor.js/dist/asciidoctor">;
}
