// flow-typed signature: f920f3d9c66f46197d121928b5687b7f
// flow-typed version: <<STUB>>/cosmiconfig_v2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cosmiconfig'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "cosmiconfig" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "cosmiconfig/lib/loadDefinedFile" {
  declare module.exports: any;
}

declare module "cosmiconfig/lib/loadJs" {
  declare module.exports: any;
}

declare module "cosmiconfig/lib/loadPackageProp" {
  declare module.exports: any;
}

declare module "cosmiconfig/lib/loadRc" {
  declare module.exports: any;
}

// Filename aliases
declare module "cosmiconfig/index" {
  declare module.exports: $Exports<"cosmiconfig">;
}
declare module "cosmiconfig/index.js" {
  declare module.exports: $Exports<"cosmiconfig">;
}
declare module "cosmiconfig/lib/loadDefinedFile.js" {
  declare module.exports: $Exports<"cosmiconfig/lib/loadDefinedFile">;
}
declare module "cosmiconfig/lib/loadJs.js" {
  declare module.exports: $Exports<"cosmiconfig/lib/loadJs">;
}
declare module "cosmiconfig/lib/loadPackageProp.js" {
  declare module.exports: $Exports<"cosmiconfig/lib/loadPackageProp">;
}
declare module "cosmiconfig/lib/loadRc.js" {
  declare module.exports: $Exports<"cosmiconfig/lib/loadRc">;
}
