// flow-typed signature: 56848df4dc23d9f45badc6098dd064d6
// flow-typed version: <<STUB>>/deep-assign_v2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deep-assign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "deep-assign" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "deep-assign/index" {
  declare module.exports: $Exports<"deep-assign">;
}
declare module "deep-assign/index.js" {
  declare module.exports: $Exports<"deep-assign">;
}
