// flow-typed signature: cd4c691226d8e9c1a0f86fb74504ac5f
// flow-typed version: <<STUB>>/dotenv-expand_v4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv-expand'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "dotenv-expand" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "dotenv-expand/lib/main" {
  declare module.exports: any;
}

// Filename aliases
declare module "dotenv-expand/lib/main.js" {
  declare module.exports: $Exports<"dotenv-expand/lib/main">;
}
