// flow-typed signature: 5071ae5ab58b0dd1a963d68c53e9721a
// flow-typed version: <<STUB>>/eslint-config-i-am-meticulous_v^7.0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-i-am-meticulous'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "eslint-config-i-am-meticulous" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "eslint-config-i-am-meticulous/_flow-globals" {
  declare module.exports: any;
}

declare module "eslint-config-i-am-meticulous/ava" {
  declare module.exports: any;
}

declare module "eslint-config-i-am-meticulous/es5" {
  declare module.exports: any;
}

declare module "eslint-config-i-am-meticulous/flow" {
  declare module.exports: any;
}

declare module "eslint-config-i-am-meticulous/react-flow" {
  declare module.exports: any;
}

declare module "eslint-config-i-am-meticulous/react-native" {
  declare module.exports: any;
}

declare module "eslint-config-i-am-meticulous/react" {
  declare module.exports: any;
}

// Filename aliases
declare module "eslint-config-i-am-meticulous/_flow-globals.js" {
  declare module.exports: $Exports<
    "eslint-config-i-am-meticulous/_flow-globals",
  >;
}
declare module "eslint-config-i-am-meticulous/ava.js" {
  declare module.exports: $Exports<"eslint-config-i-am-meticulous/ava">;
}
declare module "eslint-config-i-am-meticulous/es5.js" {
  declare module.exports: $Exports<"eslint-config-i-am-meticulous/es5">;
}
declare module "eslint-config-i-am-meticulous/flow.js" {
  declare module.exports: $Exports<"eslint-config-i-am-meticulous/flow">;
}
declare module "eslint-config-i-am-meticulous/index" {
  declare module.exports: $Exports<"eslint-config-i-am-meticulous">;
}
declare module "eslint-config-i-am-meticulous/index.js" {
  declare module.exports: $Exports<"eslint-config-i-am-meticulous">;
}
declare module "eslint-config-i-am-meticulous/react-flow.js" {
  declare module.exports: $Exports<"eslint-config-i-am-meticulous/react-flow">;
}
declare module "eslint-config-i-am-meticulous/react-native.js" {
  declare module.exports: $Exports<
    "eslint-config-i-am-meticulous/react-native",
  >;
}
declare module "eslint-config-i-am-meticulous/react.js" {
  declare module.exports: $Exports<"eslint-config-i-am-meticulous/react">;
}
