// flow-typed signature: 786772ba7faa8bb08a34713f36b54613
// flow-typed version: <<STUB>>/get-port_v2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-port'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "get-port" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "get-port/index" {
  declare module.exports: $Exports<"get-port">;
}
declare module "get-port/index.js" {
  declare module.exports: $Exports<"get-port">;
}
