// flow-typed signature: 98a9fe7ccb051a9597b6ba2753e9d302
// flow-typed version: <<STUB>>/git-exec-and-restage_v^1.0.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-exec-and-restage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "git-exec-and-restage" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "git-exec-and-restage/dist/CliError" {
  declare module.exports: any;
}

declare module "git-exec-and-restage/dist/gitUtils" {
  declare module.exports: any;
}

declare module "git-exec-and-restage/dist/index" {
  declare module.exports: any;
}

declare module "git-exec-and-restage/dist/polyfills" {
  declare module.exports: any;
}

// Filename aliases
declare module "git-exec-and-restage/dist/CliError.js" {
  declare module.exports: $Exports<"git-exec-and-restage/dist/CliError">;
}
declare module "git-exec-and-restage/dist/gitUtils.js" {
  declare module.exports: $Exports<"git-exec-and-restage/dist/gitUtils">;
}
declare module "git-exec-and-restage/dist/index.js" {
  declare module.exports: $Exports<"git-exec-and-restage/dist/index">;
}
declare module "git-exec-and-restage/dist/polyfills.js" {
  declare module.exports: $Exports<"git-exec-and-restage/dist/polyfills">;
}
