// flow-typed signature: 274e57accf92ea057b7eab3b30e2463d
// flow-typed version: <<STUB>>/globby_v^6.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'globby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "globby" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "globby/index" {
  declare module.exports: $Exports<"globby">;
}
declare module "globby/index.js" {
  declare module.exports: $Exports<"globby">;
}
