// flow-typed signature: 7df1c90ff653ead8008f05b6fa3272d1
// flow-typed version: <<STUB>>/gray-matter_v3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gray-matter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "gray-matter" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "gray-matter/lib/defaults" {
  declare module.exports: any;
}

declare module "gray-matter/lib/engine" {
  declare module.exports: any;
}

declare module "gray-matter/lib/engines" {
  declare module.exports: any;
}

declare module "gray-matter/lib/excerpt" {
  declare module.exports: any;
}

declare module "gray-matter/lib/parse" {
  declare module.exports: any;
}

declare module "gray-matter/lib/stringify" {
  declare module.exports: any;
}

declare module "gray-matter/lib/to-file" {
  declare module.exports: any;
}

declare module "gray-matter/lib/utils" {
  declare module.exports: any;
}

// Filename aliases
declare module "gray-matter/index" {
  declare module.exports: $Exports<"gray-matter">;
}
declare module "gray-matter/index.js" {
  declare module.exports: $Exports<"gray-matter">;
}
declare module "gray-matter/lib/defaults.js" {
  declare module.exports: $Exports<"gray-matter/lib/defaults">;
}
declare module "gray-matter/lib/engine.js" {
  declare module.exports: $Exports<"gray-matter/lib/engine">;
}
declare module "gray-matter/lib/engines.js" {
  declare module.exports: $Exports<"gray-matter/lib/engines">;
}
declare module "gray-matter/lib/excerpt.js" {
  declare module.exports: $Exports<"gray-matter/lib/excerpt">;
}
declare module "gray-matter/lib/parse.js" {
  declare module.exports: $Exports<"gray-matter/lib/parse">;
}
declare module "gray-matter/lib/stringify.js" {
  declare module.exports: $Exports<"gray-matter/lib/stringify">;
}
declare module "gray-matter/lib/to-file.js" {
  declare module.exports: $Exports<"gray-matter/lib/to-file">;
}
declare module "gray-matter/lib/utils.js" {
  declare module.exports: $Exports<"gray-matter/lib/utils">;
}
