// flow-typed signature: 97f9787e107e9b7a0d6e9883f913585e
// flow-typed version: <<STUB>>/husky_v^0.13.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'husky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "husky" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "husky/bin/install" {
  declare module.exports: any;
}

declare module "husky/bin/uninstall" {
  declare module.exports: any;
}

declare module "husky/src/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "husky/bin/install.js" {
  declare module.exports: $Exports<"husky/bin/install">;
}
declare module "husky/bin/uninstall.js" {
  declare module.exports: $Exports<"husky/bin/uninstall">;
}
declare module "husky/src/index.js" {
  declare module.exports: $Exports<"husky/src/index">;
}
