// flow-typed signature: ee088e07465135c5ff23e4771049cfed
// flow-typed version: <<STUB>>/lodash.flatten_v4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.flatten'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "lodash.flatten" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "lodash.flatten/index" {
  declare module.exports: $Exports<"lodash.flatten">;
}
declare module "lodash.flatten/index.js" {
  declare module.exports: $Exports<"lodash.flatten">;
}
