// flow-typed signature: 448e8acf974245701845820402e2a591
// flow-typed version: <<STUB>>/radium_v0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'radium'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "radium" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "radium/dist/radium" {
  declare module.exports: any;
}

declare module "radium/dist/radium.min" {
  declare module.exports: any;
}

declare module "radium/lib/append-important-to-each-value" {
  declare module.exports: any;
}

declare module "radium/lib/append-px-if-needed" {
  declare module.exports: any;
}

declare module "radium/lib/camel-case-props-to-dash-case" {
  declare module.exports: any;
}

declare module "radium/lib/components/style-root" {
  declare module.exports: any;
}

declare module "radium/lib/components/style-sheet" {
  declare module.exports: any;
}

declare module "radium/lib/components/style" {
  declare module.exports: any;
}

declare module "radium/lib/config" {
  declare module.exports: any;
}

declare module "radium/lib/css-rule-set-to-string" {
  declare module.exports: any;
}

declare module "radium/lib/enhancer" {
  declare module.exports: any;
}

declare module "radium/lib/get-state-key" {
  declare module.exports: any;
}

declare module "radium/lib/get-state" {
  declare module.exports: any;
}

declare module "radium/lib/hash" {
  declare module.exports: any;
}

declare module "radium/lib/index" {
  declare module.exports: any;
}

declare module "radium/lib/keyframes" {
  declare module.exports: any;
}

declare module "radium/lib/map-object" {
  declare module.exports: any;
}

declare module "radium/lib/merge-styles" {
  declare module.exports: any;
}

declare module "radium/lib/plugins/check-props-plugin" {
  declare module.exports: any;
}

declare module "radium/lib/plugins/index" {
  declare module.exports: any;
}

declare module "radium/lib/plugins/keyframes-plugin" {
  declare module.exports: any;
}

declare module "radium/lib/plugins/merge-style-array-plugin" {
  declare module.exports: any;
}

declare module "radium/lib/plugins/mouse-up-listener" {
  declare module.exports: any;
}

declare module "radium/lib/plugins/prefix-plugin" {
  declare module.exports: any;
}

declare module "radium/lib/plugins/remove-nested-styles-plugin" {
  declare module.exports: any;
}

declare module "radium/lib/plugins/resolve-interaction-styles-plugin" {
  declare module.exports: any;
}

declare module "radium/lib/plugins/resolve-media-queries-plugin" {
  declare module.exports: any;
}

declare module "radium/lib/plugins/visited-plugin" {
  declare module.exports: any;
}

declare module "radium/lib/prefixer" {
  declare module.exports: any;
}

declare module "radium/lib/resolve-styles" {
  declare module.exports: any;
}

declare module "radium/lib/style-keeper" {
  declare module.exports: any;
}

declare module "radium/lib/test-helpers" {
  declare module.exports: any;
}

declare module "radium/src/__mocks__/exenv" {
  declare module.exports: any;
}

declare module "radium/src/__mocks__/prefixer" {
  declare module.exports: any;
}

declare module "radium/src/__tests__/camel-case-props-to-dash-case-test" {
  declare module.exports: any;
}

declare module "radium/src/__tests__/enhancer-test" {
  declare module.exports: any;
}

declare module "radium/src/__tests__/get-state-test" {
  declare module.exports: any;
}

declare module "radium/src/__tests__/keyframes-test" {
  declare module.exports: any;
}

declare module "radium/src/__tests__/media-query-test" {
  declare module.exports: any;
}

declare module "radium/src/__tests__/radium-test" {
  declare module.exports: any;
}

declare module "radium/src/__tests__/remove-nested-styles-test" {
  declare module.exports: any;
}

declare module "radium/src/__tests__/resolve-styles-test" {
  declare module.exports: any;
}

declare module "radium/src/__tests__/style-component-test" {
  declare module.exports: any;
}

declare module "radium/src/__tests__/visited-test" {
  declare module.exports: any;
}

declare module "radium/src/append-important-to-each-value" {
  declare module.exports: any;
}

declare module "radium/src/append-px-if-needed" {
  declare module.exports: any;
}

declare module "radium/src/camel-case-props-to-dash-case" {
  declare module.exports: any;
}

declare module "radium/src/components/style-root" {
  declare module.exports: any;
}

declare module "radium/src/components/style-sheet" {
  declare module.exports: any;
}

declare module "radium/src/components/style" {
  declare module.exports: any;
}

declare module "radium/src/config" {
  declare module.exports: any;
}

declare module "radium/src/css-rule-set-to-string" {
  declare module.exports: any;
}

declare module "radium/src/enhancer" {
  declare module.exports: any;
}

declare module "radium/src/get-state-key" {
  declare module.exports: any;
}

declare module "radium/src/get-state" {
  declare module.exports: any;
}

declare module "radium/src/hash" {
  declare module.exports: any;
}

declare module "radium/src/index" {
  declare module.exports: any;
}

declare module "radium/src/keyframes" {
  declare module.exports: any;
}

declare module "radium/src/map-object" {
  declare module.exports: any;
}

declare module "radium/src/merge-styles" {
  declare module.exports: any;
}

declare module "radium/src/plugins/check-props-plugin" {
  declare module.exports: any;
}

declare module "radium/src/plugins/index" {
  declare module.exports: any;
}

declare module "radium/src/plugins/keyframes-plugin" {
  declare module.exports: any;
}

declare module "radium/src/plugins/merge-style-array-plugin" {
  declare module.exports: any;
}

declare module "radium/src/plugins/mouse-up-listener" {
  declare module.exports: any;
}

declare module "radium/src/plugins/prefix-plugin" {
  declare module.exports: any;
}

declare module "radium/src/plugins/remove-nested-styles-plugin" {
  declare module.exports: any;
}

declare module "radium/src/plugins/resolve-interaction-styles-plugin" {
  declare module.exports: any;
}

declare module "radium/src/plugins/resolve-media-queries-plugin" {
  declare module.exports: any;
}

declare module "radium/src/plugins/visited-plugin" {
  declare module.exports: any;
}

declare module "radium/src/prefixer" {
  declare module.exports: any;
}

declare module "radium/src/resolve-styles" {
  declare module.exports: any;
}

declare module "radium/src/style-keeper" {
  declare module.exports: any;
}

declare module "radium/src/test-helpers" {
  declare module.exports: any;
}

// Filename aliases
declare module "radium/dist/radium.js" {
  declare module.exports: $Exports<"radium/dist/radium">;
}
declare module "radium/dist/radium.min.js" {
  declare module.exports: $Exports<"radium/dist/radium.min">;
}
declare module "radium/lib/append-important-to-each-value.js" {
  declare module.exports: $Exports<"radium/lib/append-important-to-each-value">;
}
declare module "radium/lib/append-px-if-needed.js" {
  declare module.exports: $Exports<"radium/lib/append-px-if-needed">;
}
declare module "radium/lib/camel-case-props-to-dash-case.js" {
  declare module.exports: $Exports<"radium/lib/camel-case-props-to-dash-case">;
}
declare module "radium/lib/components/style-root.js" {
  declare module.exports: $Exports<"radium/lib/components/style-root">;
}
declare module "radium/lib/components/style-sheet.js" {
  declare module.exports: $Exports<"radium/lib/components/style-sheet">;
}
declare module "radium/lib/components/style.js" {
  declare module.exports: $Exports<"radium/lib/components/style">;
}
declare module "radium/lib/config.js" {
  declare module.exports: $Exports<"radium/lib/config">;
}
declare module "radium/lib/css-rule-set-to-string.js" {
  declare module.exports: $Exports<"radium/lib/css-rule-set-to-string">;
}
declare module "radium/lib/enhancer.js" {
  declare module.exports: $Exports<"radium/lib/enhancer">;
}
declare module "radium/lib/get-state-key.js" {
  declare module.exports: $Exports<"radium/lib/get-state-key">;
}
declare module "radium/lib/get-state.js" {
  declare module.exports: $Exports<"radium/lib/get-state">;
}
declare module "radium/lib/hash.js" {
  declare module.exports: $Exports<"radium/lib/hash">;
}
declare module "radium/lib/index.js" {
  declare module.exports: $Exports<"radium/lib/index">;
}
declare module "radium/lib/keyframes.js" {
  declare module.exports: $Exports<"radium/lib/keyframes">;
}
declare module "radium/lib/map-object.js" {
  declare module.exports: $Exports<"radium/lib/map-object">;
}
declare module "radium/lib/merge-styles.js" {
  declare module.exports: $Exports<"radium/lib/merge-styles">;
}
declare module "radium/lib/plugins/check-props-plugin.js" {
  declare module.exports: $Exports<"radium/lib/plugins/check-props-plugin">;
}
declare module "radium/lib/plugins/index.js" {
  declare module.exports: $Exports<"radium/lib/plugins/index">;
}
declare module "radium/lib/plugins/keyframes-plugin.js" {
  declare module.exports: $Exports<"radium/lib/plugins/keyframes-plugin">;
}
declare module "radium/lib/plugins/merge-style-array-plugin.js" {
  declare module.exports: $Exports<
    "radium/lib/plugins/merge-style-array-plugin"
  >;
}
declare module "radium/lib/plugins/mouse-up-listener.js" {
  declare module.exports: $Exports<"radium/lib/plugins/mouse-up-listener">;
}
declare module "radium/lib/plugins/prefix-plugin.js" {
  declare module.exports: $Exports<"radium/lib/plugins/prefix-plugin">;
}
declare module "radium/lib/plugins/remove-nested-styles-plugin.js" {
  declare module.exports: $Exports<
    "radium/lib/plugins/remove-nested-styles-plugin"
  >;
}
declare module "radium/lib/plugins/resolve-interaction-styles-plugin.js" {
  declare module.exports: $Exports<
    "radium/lib/plugins/resolve-interaction-styles-plugin"
  >;
}
declare module "radium/lib/plugins/resolve-media-queries-plugin.js" {
  declare module.exports: $Exports<
    "radium/lib/plugins/resolve-media-queries-plugin"
  >;
}
declare module "radium/lib/plugins/visited-plugin.js" {
  declare module.exports: $Exports<"radium/lib/plugins/visited-plugin">;
}
declare module "radium/lib/prefixer.js" {
  declare module.exports: $Exports<"radium/lib/prefixer">;
}
declare module "radium/lib/resolve-styles.js" {
  declare module.exports: $Exports<"radium/lib/resolve-styles">;
}
declare module "radium/lib/style-keeper.js" {
  declare module.exports: $Exports<"radium/lib/style-keeper">;
}
declare module "radium/lib/test-helpers.js" {
  declare module.exports: $Exports<"radium/lib/test-helpers">;
}
declare module "radium/src/__mocks__/exenv.js" {
  declare module.exports: $Exports<"radium/src/__mocks__/exenv">;
}
declare module "radium/src/__mocks__/prefixer.js" {
  declare module.exports: $Exports<"radium/src/__mocks__/prefixer">;
}
declare module "radium/src/__tests__/camel-case-props-to-dash-case-test.js" {
  declare module.exports: $Exports<
    "radium/src/__tests__/camel-case-props-to-dash-case-test"
  >;
}
declare module "radium/src/__tests__/enhancer-test.js" {
  declare module.exports: $Exports<"radium/src/__tests__/enhancer-test">;
}
declare module "radium/src/__tests__/get-state-test.js" {
  declare module.exports: $Exports<"radium/src/__tests__/get-state-test">;
}
declare module "radium/src/__tests__/keyframes-test.js" {
  declare module.exports: $Exports<"radium/src/__tests__/keyframes-test">;
}
declare module "radium/src/__tests__/media-query-test.js" {
  declare module.exports: $Exports<"radium/src/__tests__/media-query-test">;
}
declare module "radium/src/__tests__/radium-test.js" {
  declare module.exports: $Exports<"radium/src/__tests__/radium-test">;
}
declare module "radium/src/__tests__/remove-nested-styles-test.js" {
  declare module.exports: $Exports<
    "radium/src/__tests__/remove-nested-styles-test"
  >;
}
declare module "radium/src/__tests__/resolve-styles-test.js" {
  declare module.exports: $Exports<"radium/src/__tests__/resolve-styles-test">;
}
declare module "radium/src/__tests__/style-component-test.js" {
  declare module.exports: $Exports<"radium/src/__tests__/style-component-test">;
}
declare module "radium/src/__tests__/visited-test.js" {
  declare module.exports: $Exports<"radium/src/__tests__/visited-test">;
}
declare module "radium/src/append-important-to-each-value.js" {
  declare module.exports: $Exports<"radium/src/append-important-to-each-value">;
}
declare module "radium/src/append-px-if-needed.js" {
  declare module.exports: $Exports<"radium/src/append-px-if-needed">;
}
declare module "radium/src/camel-case-props-to-dash-case.js" {
  declare module.exports: $Exports<"radium/src/camel-case-props-to-dash-case">;
}
declare module "radium/src/components/style-root.js" {
  declare module.exports: $Exports<"radium/src/components/style-root">;
}
declare module "radium/src/components/style-sheet.js" {
  declare module.exports: $Exports<"radium/src/components/style-sheet">;
}
declare module "radium/src/components/style.js" {
  declare module.exports: $Exports<"radium/src/components/style">;
}
declare module "radium/src/config.js" {
  declare module.exports: $Exports<"radium/src/config">;
}
declare module "radium/src/css-rule-set-to-string.js" {
  declare module.exports: $Exports<"radium/src/css-rule-set-to-string">;
}
declare module "radium/src/enhancer.js" {
  declare module.exports: $Exports<"radium/src/enhancer">;
}
declare module "radium/src/get-state-key.js" {
  declare module.exports: $Exports<"radium/src/get-state-key">;
}
declare module "radium/src/get-state.js" {
  declare module.exports: $Exports<"radium/src/get-state">;
}
declare module "radium/src/hash.js" {
  declare module.exports: $Exports<"radium/src/hash">;
}
declare module "radium/src/index.js" {
  declare module.exports: $Exports<"radium/src/index">;
}
declare module "radium/src/keyframes.js" {
  declare module.exports: $Exports<"radium/src/keyframes">;
}
declare module "radium/src/map-object.js" {
  declare module.exports: $Exports<"radium/src/map-object">;
}
declare module "radium/src/merge-styles.js" {
  declare module.exports: $Exports<"radium/src/merge-styles">;
}
declare module "radium/src/plugins/check-props-plugin.js" {
  declare module.exports: $Exports<"radium/src/plugins/check-props-plugin">;
}
declare module "radium/src/plugins/index.js" {
  declare module.exports: $Exports<"radium/src/plugins/index">;
}
declare module "radium/src/plugins/keyframes-plugin.js" {
  declare module.exports: $Exports<"radium/src/plugins/keyframes-plugin">;
}
declare module "radium/src/plugins/merge-style-array-plugin.js" {
  declare module.exports: $Exports<
    "radium/src/plugins/merge-style-array-plugin"
  >;
}
declare module "radium/src/plugins/mouse-up-listener.js" {
  declare module.exports: $Exports<"radium/src/plugins/mouse-up-listener">;
}
declare module "radium/src/plugins/prefix-plugin.js" {
  declare module.exports: $Exports<"radium/src/plugins/prefix-plugin">;
}
declare module "radium/src/plugins/remove-nested-styles-plugin.js" {
  declare module.exports: $Exports<
    "radium/src/plugins/remove-nested-styles-plugin"
  >;
}
declare module "radium/src/plugins/resolve-interaction-styles-plugin.js" {
  declare module.exports: $Exports<
    "radium/src/plugins/resolve-interaction-styles-plugin"
  >;
}
declare module "radium/src/plugins/resolve-media-queries-plugin.js" {
  declare module.exports: $Exports<
    "radium/src/plugins/resolve-media-queries-plugin"
  >;
}
declare module "radium/src/plugins/visited-plugin.js" {
  declare module.exports: $Exports<"radium/src/plugins/visited-plugin">;
}
declare module "radium/src/prefixer.js" {
  declare module.exports: $Exports<"radium/src/prefixer">;
}
declare module "radium/src/resolve-styles.js" {
  declare module.exports: $Exports<"radium/src/resolve-styles">;
}
declare module "radium/src/style-keeper.js" {
  declare module.exports: $Exports<"radium/src/style-keeper">;
}
declare module "radium/src/test-helpers.js" {
  declare module.exports: $Exports<"radium/src/test-helpers">;
}
