// flow-typed signature: 05d02801c3654ed29f4cc39696b93275
// flow-typed version: <<STUB>>/rehype-raw_v2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rehype-raw'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rehype-raw" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "rehype-raw/index" {
  declare module.exports: $Exports<"rehype-raw">;
}
declare module "rehype-raw/index.js" {
  declare module.exports: $Exports<"rehype-raw">;
}
