// flow-typed signature: ada0d6b5b5a8bc54b7bc6442098a66d6
// flow-typed version: <<STUB>>/rehype-slug_v2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rehype-slug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rehype-slug" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "rehype-slug/index" {
  declare module.exports: $Exports<"rehype-slug">;
}
declare module "rehype-slug/index.js" {
  declare module.exports: $Exports<"rehype-slug">;
}
