// flow-typed signature: 8516381b34c681e5be987297eeed59b5
// flow-typed version: <<STUB>>/rehype-stringify_v3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rehype-stringify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rehype-stringify" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "rehype-stringify/index" {
  declare module.exports: $Exports<"rehype-stringify">;
}
declare module "rehype-stringify/index.js" {
  declare module.exports: $Exports<"rehype-stringify">;
}
