// flow-typed signature: 9679230d79db7d903e2e765077ac4180
// flow-typed version: <<STUB>>/rehype-autolink-headings_v2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rehype-autolink-headings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rehype-autolink-headings" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "rehype-autolink-headings/index" {
  declare module.exports: $Exports<"rehype-autolink-headings">;
}
declare module "rehype-autolink-headings/index.js" {
  declare module.exports: $Exports<"rehype-autolink-headings">;
}
