// flow-typed signature: b4622af126b6a810a28f2c32c9f850e3
// flow-typed version: <<STUB>>/rehype-highlight_v2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rehype-highlight'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rehype-highlight" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "rehype-highlight/index" {
  declare module.exports: $Exports<"rehype-highlight">;
}
declare module "rehype-highlight/index.js" {
  declare module.exports: $Exports<"rehype-highlight">;
}
