// flow-typed signature: f8e6dcc4a22a05662c0b5760c3ffbb59
// flow-typed version: <<STUB>>/rehype-react_v3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rehype-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rehype-react" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "rehype-react/index" {
  declare module.exports: $Exports<"rehype-react">;
}
declare module "rehype-react/index.js" {
  declare module.exports: $Exports<"rehype-react">;
}
