// flow-typed signature: f39d9df4dad71bed08c2b6875600f4e7
// flow-typed version: <<STUB>>/remark-highlights_v*/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-highlights'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "remark-highlights" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "remark-highlights/src/index" {
  declare module.exports: any;
}

declare module "remark-highlights/src/utils/constructConfig" {
  declare module.exports: any;
}

declare module "remark-highlights/src/utils/getIcon" {
  declare module.exports: any;
}

declare module "remark-highlights/src/utils/highlightLines" {
  declare module.exports: any;
}

declare module "remark-highlights/src/utils/highlightNode" {
  declare module.exports: any;
}

declare module "remark-highlights/src/utils/iconsDb" {
  declare module.exports: any;
}

declare module "remark-highlights/src/utils/loadGrammars" {
  declare module.exports: any;
}

declare module "remark-highlights/src/utils/scopeNameFromLang" {
  declare module.exports: any;
}

declare module "remark-highlights/src/utils/wrapNode" {
  declare module.exports: any;
}

// Filename aliases
declare module "remark-highlights/src/index.js" {
  declare module.exports: $Exports<"remark-highlights/src/index">;
}
declare module "remark-highlights/src/utils/constructConfig.js" {
  declare module.exports: $Exports<
    "remark-highlights/src/utils/constructConfig"
  >;
}
declare module "remark-highlights/src/utils/getIcon.js" {
  declare module.exports: $Exports<"remark-highlights/src/utils/getIcon">;
}
declare module "remark-highlights/src/utils/highlightLines.js" {
  declare module.exports: $Exports<
    "remark-highlights/src/utils/highlightLines"
  >;
}
declare module "remark-highlights/src/utils/highlightNode.js" {
  declare module.exports: $Exports<"remark-highlights/src/utils/highlightNode">;
}
declare module "remark-highlights/src/utils/iconsDb.js" {
  declare module.exports: $Exports<"remark-highlights/src/utils/iconsDb">;
}
declare module "remark-highlights/src/utils/loadGrammars.js" {
  declare module.exports: $Exports<"remark-highlights/src/utils/loadGrammars">;
}
declare module "remark-highlights/src/utils/scopeNameFromLang.js" {
  declare module.exports: $Exports<
    "remark-highlights/src/utils/scopeNameFromLang"
  >;
}
declare module "remark-highlights/src/utils/wrapNode.js" {
  declare module.exports: $Exports<"remark-highlights/src/utils/wrapNode">;
}
