// flow-typed signature: e27f3c65d7624876119bbf776e5cb235
// flow-typed version: <<STUB>>/remark-toc_v4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-toc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "remark-toc" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "remark-toc/index" {
  declare module.exports: $Exports<"remark-toc">;
}
declare module "remark-toc/index.js" {
  declare module.exports: $Exports<"remark-toc">;
}
