// flow-typed signature: e4ac33d5d37539c04d320904d310ec8b
// flow-typed version: <<STUB>>/rss_v1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rss" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "rss/Gruntfile" {
  declare module.exports: any;
}

declare module "rss/lib/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "rss/Gruntfile.js" {
  declare module.exports: $Exports<"rss/Gruntfile">;
}
declare module "rss/lib/index.js" {
  declare module.exports: $Exports<"rss/lib/index">;
}
