// flow-typed signature: 2b128321185af2b6a97558b54ffcfa50
// flow-typed version: <<STUB>>/socket.io-client_v1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socket.io-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "socket.io-client" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "socket.io-client/dist/socket.io" {
  declare module.exports: any;
}

declare module "socket.io-client/dist/socket.io.min" {
  declare module.exports: any;
}

declare module "socket.io-client/dist/socket.io.slim" {
  declare module.exports: any;
}

declare module "socket.io-client/dist/socket.io.slim.min" {
  declare module.exports: any;
}

declare module "socket.io-client/lib/index" {
  declare module.exports: any;
}

declare module "socket.io-client/lib/manager" {
  declare module.exports: any;
}

declare module "socket.io-client/lib/on" {
  declare module.exports: any;
}

declare module "socket.io-client/lib/socket" {
  declare module.exports: any;
}

declare module "socket.io-client/lib/url" {
  declare module.exports: any;
}

// Filename aliases
declare module "socket.io-client/dist/socket.io.js" {
  declare module.exports: $Exports<"socket.io-client/dist/socket.io">;
}
declare module "socket.io-client/dist/socket.io.min.js" {
  declare module.exports: $Exports<"socket.io-client/dist/socket.io.min">;
}
declare module "socket.io-client/dist/socket.io.slim.js" {
  declare module.exports: $Exports<"socket.io-client/dist/socket.io.slim">;
}
declare module "socket.io-client/dist/socket.io.slim.min.js" {
  declare module.exports: $Exports<"socket.io-client/dist/socket.io.slim.min">;
}
declare module "socket.io-client/lib/index.js" {
  declare module.exports: $Exports<"socket.io-client/lib/index">;
}
declare module "socket.io-client/lib/manager.js" {
  declare module.exports: $Exports<"socket.io-client/lib/manager">;
}
declare module "socket.io-client/lib/on.js" {
  declare module.exports: $Exports<"socket.io-client/lib/on">;
}
declare module "socket.io-client/lib/socket.js" {
  declare module.exports: $Exports<"socket.io-client/lib/socket">;
}
declare module "socket.io-client/lib/url.js" {
  declare module.exports: $Exports<"socket.io-client/lib/url">;
}
